jobtest:
  stage: test
  before_script:
    - sudo apt -y update
    - sudo apt -y install apt-utils
    - sudo apt -y install net-tools python3.8 python3-pip mysql-client libmysqlclient-dev
    - sudo apt -y upgrade
    - ./init.sh

  script:
    - pwd
    - ls -al
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py check
    - python manage.py test --pattern="*_test.py"
